[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "buildforcing"
version = "0.1.0"
description = "A utility for creating forcing files in a netCDF format."
authors = [
    { name = "Chris Cox", email = "christopher.cox@student.nmt.edu" }
]
dependencies = [
    "requests",
    "pandas",
    "xarray",
    "timezonefinder",
]

