[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "buildforcing"
version = "0.11.1"
description = "A utility for creating forcing files in a netCDF format."
authors = [
    { name = "Chris Cox", email = "christopher.cox@student.nmt.edu" }
]
dependencies = [
    "requests",
    "pandas",
    "xarray",
    "netCDF4",
    "timezonefinder",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test*.py"
pythonpath = "."
